graph TD
    A[nb-public] --> B[.github];
    A --> C[assets];
    A --> D[docs];
    A --> E[README.md];

    B --> B1[workflows];
    B1 --> B1a[link-check.yml];
    B1 --> B1b[markdownlint.yml];
    B1 --> B1c[mermaid-to-svg.yml];
    B1 --> B1d[move-root-md-to-docs.yml];

    C --> C1[overview.mermaid];
    C --> C2[overview.png];

    D --> D2[assist.md];
    D --> D3[file.md];
    D --> D4[index.md];
    D --> D5[usage.md];
